plugins {
    id 'com.android.application'
}

android {
    namespace 'mx.gob.sanpedro.visorurbano'
    compileSdk 35

    defaultConfig {
        applicationId 'mx.gob.sanpedro.visorurbano'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "1.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
